### ISSUE TITLE
mdl snap failed when the working directory contains non-ASCII characters

### ISSUE THREAD

**Issue by brlin-tw** [snapcrafters/mdl#5]
## Reproduce
```shell
mkdir -p ~/非ASCII範圍路徑測試
touch ~/非ASCII範圍路徑測試/README.md
pushd ~/非ASCII範圍路徑測試
mdl README.md
popd
```

## Expected behavior
mdl runs properly

## Current behavior
mdl crashes with

```
/snap/mdl/140/lib/ruby/2.4.0/pathname.rb:41:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
        from /snap/mdl/140/lib/ruby/2.4.0/pathname.rb:41:in `chop_basename'
        from /snap/mdl/140/lib/ruby/2.4.0/pathname.rb:143:in `del_trailing_separator'
        from /snap/mdl/140/lib/ruby/2.4.0/pathname.rb:331:in `ascend'
        from /snap/mdl/140/lib/ruby/gems/2.4.0/gems/mdl-0.9.0/lib/mdl/cli.rb:167:in `probe_config_file'
        from /snap/mdl/140/lib/ruby/gems/2.4.0/gems/mdl-0.9.0/lib/mdl/cli.rb:111:in `run'
        from /snap/mdl/140/lib/ruby/gems/2.4.0/gems/mdl-0.9.0/lib/mdl.rb:14:in `run'
        from /snap/mdl/140/lib/ruby/gems/2.4.0/gems/mdl-0.9.0/bin/mdl:10:in `<top (required)>'
        from /snap/mdl/140/bin/mdl:23:in `load'
        from /snap/mdl/140/bin/mdl:23:in `<main>'
```

should be an encoding dealing problem, refer PR #6 for the patch

**Comment by N0rbert** [comment]
Still a problem for stable snap. Works only with edge.

**Comment by lucyllewy** [comment]
@igorljubuncic do you know who has access to this snap to push edge to stable? it has been sat in edge for a year now, so I think it's had enough testing....?

**Comment by ghost** [comment]
The last build on this failed a while back. I can try to rebuild, see what gives. I'll also add protection for the branches, but in general everyone in the Reviewers team is a maintainer.

**Comment by N0rbert** [comment]
Still a problem for stable snap. Works only with edge.
